version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  performance-test:
    image: swift-nio-ssl:22.04-5.8

  shell:
    image: swift-nio-ssl:22.04-5.8
