version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"

  unit-tests:
    image: swift-nio-ssl:22.04-5.10

  integration-tests:
    image: swift-nio-ssl:22.04-5.10

  documentation-check:
    image: swift-nio-ssl:22.04-5.10

  test:
    image: swift-nio-ssl:22.04-5.10
    environment:
      - MAX_ALLOCS_ALLOWED_simple_handshake=743000
      - MAX_ALLOCS_ALLOWED_many_writes=201000
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  performance-test:
    image: swift-nio-ssl:22.04-5.10

  cxx-interop-build:
    image: swift-nio-ssl:22.04-5.10

  shell:
    image: swift-nio-ssl:22.04-5.10
