version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:16.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1"

  unit-tests:
    image: swift-nio-ssl:16.04-5.1

  integration-tests:
    image: swift-nio-ssl:16.04-5.1

  test:
    image: swift-nio-ssl:16.04-5.1
    environment:
      - SANITIZER_ARG=--sanitize=thread
      - MAX_ALLOCS_ALLOWED_simple_handshake=740000
      - MAX_ALLOCS_ALLOWED_many_writes=201000

  performance-test:
    image: swift-nio-ssl:16.04-5.1

  shell:
    image: swift-nio-ssl:16.04-5.1
