version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:22.04-5.10
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.10"

  performance-test:
    image: swift-nio-ssl:22.04-5.10

  shell:
    image: swift-nio-ssl:22.04-5.10
