version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:22.04-5.8
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.8-jammy"

  unit-tests:
    image: swift-nio-ssl:22.04-5.8

  integration-tests:
    image: swift-nio-ssl:22.04-5.8

  test:
    image: swift-nio-ssl:22.04-5.8
    environment:
      - MAX_ALLOCS_ALLOWED_simple_handshake=743000
      - MAX_ALLOCS_ALLOWED_many_writes=201000
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  performance-test:
    image: swift-nio-ssl:22.04-5.8

  shell:
    image: swift-nio-ssl:22.04-5.8
