version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:16.04-4.0.3
    build:
      args:
        ubuntu_version : "16.04"
        swift_version : "4.0.3"

  test:
    image: swift-nio-ssl:16.04-4.0.3
