version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:18.04-5.0
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.0"

  unit-tests:
    image: swift-nio-ssl:18.04-5.0

  integration-tests:
    image: swift-nio-ssl:18.04-5.0

  test:
    image: swift-nio-ssl:18.04-5.0

  performance-test:
    image: swift-nio-ssl:18.04-5.0

  shell:
    image: swift-nio-ssl:18.04-5.0
