version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:18.04-5.0
    build:
      args:
        ubuntu_version: "18.04"
        swift_version: "5.0"
        skip_ruby_from_ppa: "true"

  test:
    image: swift-nio-ssl:18.04-5.0
