version: "3"

services:

  runtime-setup:
    image: swift-nio-ssl:18.04-5.0
    build:
      args:
        ubuntu_version: "18.04"
        swift_version: "5.0"
        swift_flavour: "DEVELOPMENT-SNAPSHOT-2019-01-23-a"
        swift_builds_suffix: "branch"
        skip_ruby_from_ppa: "true"

  test:
    image: swift-nio-ssl:18.04-5.0
