name: Main

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 8,20 * * *"

jobs:
    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_10_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error"
            linux_6_0_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
            linux_6_1_arguments_override: "-Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
            linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
            linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

    construct-integration-test-matrix:
        name: Construct integration matrix
        runs-on: ubuntu-latest
        outputs:
            integration-test-matrix: '${{ steps.generate-matrix.outputs.integration-test-matrix }}'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - id: generate-matrix
              run: echo "integration-test-matrix=$(curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/generate_matrix.sh | bash)" >> "$GITHUB_OUTPUT"
              env:
                  MATRIX_LINUX_SETUP_COMMAND: apt-get update -y && apt-get install -yq execstack lsof dnsutils netcat-openbsd net-tools expect curl jq
                  MATRIX_LINUX_COMMAND: ./scripts/integration_tests.sh -f test_01_renegotiation

    integration-test:
        name: Integration test
        needs: construct-integration-test-matrix
        uses: apple/swift-nio/.github/workflows/swift_test_matrix.yml@main
        with:
            name: "Integration test"
            matrix_string: '${{ needs.construct-integration-test-matrix.outputs.integration-test-matrix }}'

    benchmarks:
        name: Benchmarks
        uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
        with:
            benchmark_package_path: "Benchmarks"

    macos-tests:
        name: macOS tests
        uses: apple/swift-nio/.github/workflows/macos_tests.yml@main
        with:
            runner_pool: nightly
            build_scheme: swift-nio-ssl-Package
